### PR TITLE
Add `node_confirms` option to write messages

### PR DESCRIPTION
**Pull request by russelldb**
For  KV/counter/datatypes all

(Needed by https://github.com/nhs-riak/riak_kv/pull/8)

### CODE REVIEW

**Comment by martinsumner** [comment]
+1

**Comment by martinsumner** [comment]
Just to clarify on use of encode_quorum.  Should we allow clients to enter all or quorum for example?

**Comment by russelldb** [comment]
I'm not sure myself. On a re-read of the HTTP API code and the fsm code, it looks like the answer is a tentative "yes". Maybe @ramensen has an opinion. AFAICT this is just another write quorum option. Although not around consistency (but durability) so the meaning of `quorum` in this case is probably `2` by default, but I think it makes sense to leave it as a shortcut for buckets that are not default `n=3`.

**Comment by martinsumner** [comment]
I'm happy with that

**Pull request merged**
